<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net9.0</TargetFrameworks>
    <Authors>HatTrick Labs</Authors>
    <Description>Reflection utilities.</Description>
    <Copyright>Hat Trick Labs</Copyright>
    <PackageProjectUrl>https://github.com/HatTrickLabs/reflect</PackageProjectUrl>
    <RepositoryUrl>https://github.com/HatTrickLabs/reflect</RepositoryUrl>
    <NeutralLanguage>en-US</NeutralLanguage>
    <PackageTags>reflection expression</PackageTags>
    <GeneratePackageOnBuild>false</GeneratePackageOnBuild>
    <Version>3.0.0</Version>
    <PackageReleaseNotes>Limited build target to net9.0.
Expanded usage of ReadOnlySpan of char where possible.
Implemented helper Func registration for hot paths on with known bind expressions.</PackageReleaseNotes>
    <Company>HatTrick Labs LLC</Company>
    <PackageLicenseExpression>Apache-2.0</PackageLicenseExpression>
    <PackageIcon>htl-nuget-logo.png</PackageIcon>
    <PackageIconUrl />
    <RepositoryType>git</RepositoryType>
  </PropertyGroup>
  <ItemGroup>
    <None Include="..\..\build\htl-nuget-logo.png">
      <Pack>True</Pack>
      <PackagePath>
      </PackagePath>
    </None>
  </ItemGroup>
  <ItemGroup>
    <Folder Include="Properties\PublishProfiles\" />
  </ItemGroup>
</Project>